### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ankostis** [n8henrie/pycookiecheat#2]
Thank you for your very convenient utility.

Would it be possible to decrypt cookies also on Window Chrome?

**Comment by n8henrie** [comment]
Sorry, I guess the only mention of this is hidden [in some comments](http://n8henrie.com/2013/11/use-chromes-cookies-for-easier-downloading-with-python-requests/#comment-1439903383) far below the homepage. Basically, I don't have Windows, so I won't be putting that in. If you'd like to make a PR that would be awesome. I should add this to the readme.

**Comment by dani14-96** [comment]
Hi! Awesome utility! I'd like to use it with a python script in Windows, but it's not supported (like you said). So I'm going to try to modify it so that you can use it in Windows. 
I'm a programming begginer so I don't know what possible differences could have Windows and Unix in this sense. What could them be?

**Comment by n8henrie** [comment]
Great question -- like I said above, I don't use or have access to Windows, so I can't tell you. Let me know if you make progress on this front.

**Comment by n8henrie** [comment]
Closing for lack of interest.

**Comment by stegr04** [comment]
Hi @n8henrie , 

Adding windows support is something I just setup in a fork of your project. I'd like to offer it back in the form of a pull request. But, before I did that had some questions:
1. Would you like a seaparate issue to be created? I've never done a pull request before. 
2. I'd seen, in a different issue for windows support, where you recommended setting up tests. I'm okay with doing this. But if you could give any guidance on this (best approach, reuse something you have, where to look, etc..). I've not done this before either. 

I've also noticed a scenario where the jsessionid and session-id are out of sync. I'm not sure if this is the result of the site needing to clean things up and its not, if the browser should be cleaning it up but its not, etc.. but it is something I'm also interested in seeing how I can handle this situation. I can do two different pull requests if you'd like these changes too. 

Thanks, 
G

**Comment by n8henrie** [comment]
That's great! 

> Would you like a seaparate issue to be created?

No, I'll re-open this one.

> where you recommended setting up tests

Yes, tests are pretty important -- especially since I don't have a Windows machine to help ensure that I'm not breaking this when I make changes on my end. What these tests will look like may depend on the code you're adding, and where it differs from Unix systems.

I am about to be mostly unavailable for 10 days or so, just FYI.

**Comment by stegr04** [comment]
Hi @n8henrie ,
Sounds good, thanks! Sorry I've not responded sooner. Had a few things come up in the meantime and I actually deleted my original fork since I was writing all my changes to my master branch instead of using a separate branch. Now that I've got that all squared away, just a few questions:
1. Would you like me to send the pull request to your dev or master branch? The changes I made were to a branch based on your master branch. 
2. I'm fully on board with the need to write tests. I'm just not familiar with writing them. I see there is a test_pycookiecheat.py in the tests folder. Should I use that to try as a baseline to test on Windows? I've never done anything with travis but I don't mind doing the legwork to get it done. Based on your response it sounded like you'd want to read the changes first and could then offer suggestions on what tests to run. 

Sorry for the noob questions/comments. :) Hope you're enjoying some time off. 

Cheers,
G

**Comment by n8henrie** [comment]
> Hope you're enjoying some time off.

Thanks, we did :)

> Would you like me to send the pull request to your dev or master branch?

Thanks for pointing out ambiguity here, I have updated my contributing guidelines (at least on the dev branch): https://github.com/n8henrie/pycookiecheat/blob/dev/CONTRIBUTING.md

In short, you should base your branch on `dev` and the PR should go back to my `dev` branch.

> I'm fully on board with the need to write tests. I'm just not familiar with writing them.

Awesome, definitely a great habit to get into!

> Should I use that to try as a baseline to test on Windows?

Yes. It's tough, I'm not entirely sure whether additional tests for windows will be helpful, but at minimum the existing tests should pass. In general, one of the roles of tests is so that changes can be made in the future with some reassurance that I'm not breaking the work you've done. But I don't think the automated test environments (e.g. travis) generally run on Windows, so I'm not sure how helpful it will be to run windows-specific tests. However, if you find that the current code is not working on Windows, and you need to make a change to get it to work, it would probably be a good idea to add a test that fails with the current codebase and then passes with your changes. Does that make sense?

Thanks for your willingness to learn, we're all noobs here :)
