### ISSUE TITLE
Depend on pycryptodome instead of pycrypto

### ISSUE THREAD

**Issue by vcheckzen** [n8henrie/pycookiecheat#24]
This package should depend on pycryptodome instead of pycrypto, as it is a actively maintained drop-in replacement for pycrypto. Pycrypo has issues installing on Windows, and hasn't been maintained since ~2013.

Due to the install issue I'm having to temporarily fork this library, since overriding dependencies is apparently quite difficult to do.

**Comment by n8henrie** [comment]
I may go back to [cryptography](https://github.com/pyca/cryptography) at some point, but for now pycrypto seems to be working fine for [the officially supported platforms](https://github.com/n8henrie/pycookiecheat#how-about-windows).

Thanks for bringing my attention to [pycryptodome](https://www.pycryptodome.org/en/latest/), I'll check it out, especially if I ever want to bring pycookiecheat to windows.

**Comment by michaeljoseph** [comment]
Given https://github.com/pyupio/safety-db/issues/2252 (https://www.cvedetails.com/cve/CVE-2013-7459/), perhaps this is a good moment to switch to `pycryptodome` or `cryptography`?

**Comment by n8henrie** [comment]
Thanks for pointing this out. I had moved away from cryptography due to
difficulties with installation, but this was pre 2.0 and it looks like they
now have wheels that should make this much more streamlined.

https://cryptography.io/en/latest/installation/#building-cryptography-on-linux

> cryptography ships manylinux wheels (as of 2.0) so all dependencies are
included.

Here is the commit of interest that I would need to reverse:

https://github.com/n8henrie/pycookiecheat/commit/17573afcf25ac29090bd4b3ef253f4d7c9937907

I like the fact that cryptography is supported by an organization:
https://github.com/orgs/pyca/people -- pycryptodome seems interesting, but
I'd probably prefer cryptography for now.

**Comment by michaeljoseph** [comment]
👍  to `cryptography`, but please consider switching to `pycryptodome` in the short term to appease security scanners?

**Comment by michaeljoseph** [comment]
🙌 👍
