### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by FuhuXia** [n8henrie/pycookiecheat#29]
- **Operating system and version**: macOS 10.13.6
- **Python version**: 3.7.4
- **pycookiecheat version**: v0.4.5

## After making a few thousand of requests, it gives error
```
...pycookiecheat.py, line 273, in chrome_cookies
   ) in conn.execute(sql, (host_key,)):
sqlite3.OperationalError: database is locked
``` 
A work-around is to close Chrome and re-open Chrome to be able to continue making more requests.

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and pycookiecheat version in your issue
- [x] Ensure you're running a supported version of Python
- [ ] Run pycookiecheat in debug mode if applicable and include
  relevant output
- [x] Search the existing (including closed) issues
- [x] Please use [codeblocks][1] for any code, config, program output, etc.

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Huh, thanks for the report. Can I ask about your use case? Are you retrieving cookies for thousands of URLs at once? Or doing so over time (i.e. a long-running process)?

Are you browsing while requesting the cookies? I know Chrome does lock the file at times; I generally recommend quitting the application prior to using pycookiecheat to avoid issues here.

**Comment by FuhuXia** [comment]
I have a list of 30k URLs. I am processing them one by one over time. The whole process usually take 1+ hour. Sometimes it finishes fine from beginning to end, sometimes it has this glitch 2-3 times during the process.

I occasionally browse the site to keep session live. The glitch happen on its own, not when I am browsing.

**Comment by n8henrie** [comment]
Yes, I have also run into a similar intermittent error when trying to access the cookie file while Chrome is running. I don't know of a better solution than not running while browsing, since Chrome seems to lock the database on occasion.

Perhaps there are some SQLITE flags to open with read-only access that bypass locking concerns?

**Comment by n8henrie** [comment]
Looks like this may be out of my control:

https://stackoverflow.com/questions/7857755/is-it-possible-to-open-a-locked-sqlite-database-in-read-only-mode

Unclear if adding `?mode=ro` may help: https://docs.python.org/3.8/library/sqlite3.html#sqlite3.connect

**Comment by n8henrie** [comment]
Please see if https://github.com/n8henrie/pycookiecheat/commit/230574e9e19b3883f7a6fea17d8fa365d385b505 helps

**Comment by n8henrie** [comment]
Bump.

This issue is pending a response and is blocked until I have more info. To keep the issue list groomed, I will often close these stalled issues if they go a prolonged time without a response. In this case, I will give it another week or so.

**Comment by ozgen92** [comment]
@n8henrie I had the same problem, and probably related information: I was using a lot of concurrent calls.

I found the process that has locked the file and it seems to be:
oezgen             637   0.0  0.2  4681680  26532   ??  S     5Nov19 183:07.43 /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/78.0.3904.70/Helpers/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper --type=utility --field-trial-handle=1718379636,13217150702388057384,3641183978531146804,131072 --lang=en-US --service-sandbox-type=network --service-request-channel-token=5198092952403259345

I think Google Chrome was also using the cookies for the same pages
So I'm not sure what in particular caused the problem but for those who ended up here and looking for quick fix (on mac):

```
 fuser /Users/<USERNAME_HERE>/Library/Application\ Support/Google/Chrome/Default/Cookies
/Users/oezgen/Library/Application Support/Google/Chrome/Default/Cookies: <SOME_PID>
 kill -9 <SOME_PID>
```

**Comment by n8henrie** [comment]
Thanks for chiming in. Would you mind trying the dev branch (which includes a commit to open in read-only mode) and see if you still have this issue?

**Comment by ozgen92** [comment]
@n8henrie thanks for the quick fix (and sorry for the late reply from my side)

I haven't had this problem since my last comment, although I am still using a lot of concurrent calls. I'm not sure how I triggered it before...

I will start using dev branch with pycookiecheat and post more details here if I encounter the same issue again.

**Comment by n8henrie** [comment]
Sounds good, thanks for the update.

**Comment by NightMachinary** [comment]
[**@n8henrie**](https://github.com/n8henrie) commented on [Jan 26, 2020, 5:53 PM GMT+3:30](https://github.com/n8henrie/pycookiecheat/issues/29#issuecomment-578506495 "2020-01-26T14:23:11Z - Replied by Github Reply Comments"):
> Thanks for chiming in. Would you mind trying the dev branch (which includes the commit linked above to open in read-only mode) and see if you still have this issue?

Is this commit still in the dev branch? I just installed `git+https://github.com/n8henrie/pycookiecheat.git@dev`, and I still get

```
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/Users/evar/anaconda/lib/python3.7/site-packages/pycookiecheat/pycookiecheat.py", line 248, in chrome_cookies
    ) in conn.execute("PRAGMA table_info(cookies)"):
sqlite3.OperationalError: database is locked
```

**Comment by n8henrie** [comment]
Comparing the commit I linked above: https://github.com/n8henrie/pycookiecheat/commit/230574e9e19b3883f7a6fea17d8fa365d385b505 with the current dev branch: https://github.com/n8henrie/pycookiecheat/blob/e8e9893bb5c7f4f9d0514e605a5412892f97f912/src/pycookiecheat/pycookiecheat.py#L234 it looks like it is.

So I guess that commit didn't prevent the issue, though it still seems like a good idea (since there's no reason my library should be modifying anything at this point).

So I think there is some other process, likely Chrome or a leftover background process from Chrome but possibly something else, that has the db locked.
