### ISSUE TITLE
Get AttributeError Only with crontab

### ISSUE THREAD

**Issue by FatGhosta** [n8henrie/pycookiecheat#8]
I wrote a python program using pycookiecheat.  
When I run it with the command `python myprogram.py`, it will run **successfully**.  
However, I run it in crontab with the config below:
```
* * * * * /usr/bin/python  /Users/fatghosta/workspace/myprogram.py >> /Users/fatghosta/workspace/myprogram.log
```
I get some error below:
```
Traceback (most recent call last):
  File "/Users/fatghosta/workspace/myprogram.py", line 33, in <module>
    cookies = chrome_cookies("http://xx.xxx.com")
  File "/Library/Python/2.7/site-packages/pycookiecheat-0.2.0-py2.7.egg/pycookiecheat/pycookiecheat.py", line 61, in chrome_cookies
    my_pass = my_pass.encode('utf8')
AttributeError: 'NoneType' object has no attribute 'encode'
``` 

My OS version is OS X 10.10.5.  
I setup pycookiecheat by cloning pycookiecheat.git and then "python setup.py install".

**Comment by FatGhosta** [comment]
I install pycookiecheat in master branch.

**Comment by n8henrie** [comment]
Thanks for bringing up this issue, hopefully we'll get it figured out.

What operating system are you using? Looks like OSX?

Did you copy that traceback or retype it? because in the traceback I see `my_pass = my_passencode('utf8')` but it needs the `.` (`my_pass = my_pass.encode('utf8')`), so my guess is that you didn't paste it directly.

On thing to check will be your python path; open up a terminal and type `command -v python` and see if it resolves to `/usr/bin/python`. If it goes to a different python like `/usr/local/bin/python`, then that may be part of the problem.

More likely, I think the problem may be more related to the user running `crontab`. Are you running it as root? If so, pycookiecheet may be looking for the cookies in the home directory of `root` instead of your usual user.

If this is the issue, you may be able to get it to work by using `sudo -u fatghosta` before the `/usr/bin/python  /Users/fatghosta/workspace/myprogram.py >> /Users/fatghosta/workspace/myprogram.log`

Let me know if that works.

**Comment by FatGhosta** [comment]
first, I indeed use OSX, the version is 10.10.5.  
  
second, I can see the `.` in the traceback, I didn't miss it. I don't know why you can't see. But it doesn't matter.  

In the begining, I also though the problem is about the version of Python. But I get my python path (`/usr/bin/python`) via `whereis python` and `which python`. Now, type `command -v python`, get same one. 

I also run it successfully as root,  and fail to run it on crontab of root.  Same error.  
 
using `sudo -u fatghosta`, it didn't work.

By Google, I find there is something wrong with keyring and crontab.
http://ubuntuforums.org/showthread.php?t=1671248
http://stackoverflow.com/questions/20978982/python-keyring-and-cron

**Comment by n8henrie** [comment]
Odd, I can see the period in the traceback on GitHub, but it is not there in the notification email. 

![](http://f.cl.ly/items/370a0x3C3T1S361h3m1N/ClouDrop%20Jan%209,%202016,%2010%3A22%3A47%20AM%20Jan%209,%202016,%2010%3A22%3A47%20AM.png)

Now that I know for sure you're on OS X I'll give it a shot and see if I can figure something out.

**Comment by n8henrie** [comment]
Looks like that thread is about [`gnome-keyring`](https://wiki.gnome.org/GnomeKeyring), not [`python-keyring`](https://github.com/jaraco/keyring).

**Comment by n8henrie** [comment]
Do you get a pop-up requesting permission when you run it interactively?

For example, if you run: `python3 -c "from pycookiecheat import chrome_cookies; from pprint import pprint; pprint(chrome_cookies('https://github.com'))"`

If I run that, or if I put it into a bash script and run that, I get a popup requesting permission. Can't remember if this was an issue before OS X 10.11 (what I'm running).

The popup:

![Uploading Screen Shot 2016-01-09 at 11.30.32 AM.jpg…]()

**Comment by n8henrie** [comment]
I've been messing with it today and haven't had much luck using cron. I'm not sure, but I think the problem may be that you can't allow the permissions with the above window, since `python-keyring` [uses the `security` command](https://github.com/jaraco/keyring/blob/master/keyring/backends/OS_X.py), which won't work without permission on the above popup.

Alternatively, perhaps there's some environment variable that's missing and it's looking in the wrong keychain? Unfortunately I don't see a way to specify the appropriate keychain in `python-keyring`.

On the other hand, I did make a launchd LaunchAgent that seems to run it just fine after choosing "Always Allow" on the popup.

Make the below into `vim ~/Library/LaunchAgents/com.n8henrie.keyring_test.plist`, replacing occurrences of my username with your own, and replacing with the correct python and log paths obviously:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.n8henrie.keyring_test</string>
        <key>ProgramArguments</key>
        <array>
            <string>/usr/local/bin/python3</string>
            <string>/Users/n8henrie/tmp/fake.py</string>
        </array>
        <key>StartInterval</key>
        <integer>30</integer>
        <key>StandardOutPath</key>
        <string>/Users/n8henrie/tmp/fake.log</string>
        <key>StandardErrorPath</key>
        <string>/Users/n8henrie/tmp/fake_error.log</string>
    </dict>
</plist>
```

Afterwards, load it and it should run every 30 seconds, e.gg:

```bash
launchctl load ~/Library/LaunchAgents/com.n8henrie.keyring_test.plist
launchctl start com.n8henrie.keyring_test
```

Then just `tail -f fake.log` and you should see the cookies start pouring in after you've given permission to the script with the permissions popup above. I'll let you know if I have any breakthroughs with cron, but otherwise hopefully this is a viable workaround.

**Comment by FatGhosta** [comment]
I got the popup first time I run it interactively. And I chose "Allow" (not Always Allow) probably.

**Comment by FatGhosta** [comment]
Thank you for your patience. 
I will try it with LaunchAgents.

**Comment by n8henrie** [comment]
As you can see in the above issue, the problem seems to be that the cron environment makes `security` use a different default keychain (for example, evaluate the output of the command `security default-keychain` in a regular terminal and then as a cron command). `python-keyring` [depends on `security`](https://github.com/jaraco/keyring/blob/master/keyring/backends/OS_X.py#L107) to get the password from the OS X Keychain, so when the `default-keychain` changes, it won't work.

I've added a workaround to allow users to specify a keychain to use and submitted it (https://github.com/jaraco/keyring/pull/190), but I think the better solution might be to avoid the whole issue and use the launchd plist I provided above.

**Comment by n8henrie** [comment]
My commit was [merged into Keyring](https://github.com/jaraco/keyring/commit/3b492a948ca78eec3ac27cca7fc9c23f5919da0a), solving the issue, so it should now work with cron as well as launchd.

**Comment by FatGhosta** [comment]
Cool!
